if: branch = master

sudo: required

services:
  - docker                  

before_install:            
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output *.adoc      
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf -D /documents/output *.adoc    

after_error: 
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_success:      
  - git clone ${GH_REF} --single-branch --branch gh-pages gh-pages
  - cd gh-pages
  - cp ../*.html ../*.pdf .
  - mkdir -p images
  - cp ../images/*.png images/
  - git config user.name "TravisCI"
  - git config user.email "build-pipeline@travis-ci.org"
  - git add images *.html *.pdf
  - git commit -m "Update GitHub Pages"
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages
